version: '3'

services:
  v2ray-tls:
    image: spartans1179/v2ray-tls:latest
    restart: always
    volumes:
      - ./config/config.json:/etc/v2ray/config.json

  web-server:
    image: spartans1179/web-server:latest
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: always
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - ./files/web-server:/root/.caddy
    depends_on:
      - v2ray-tls
    ports:
      - 443:443
      - 80:80
